name=sig
name=sig=src=class=1
namenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename=sigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsig=srcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrc=classclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclass=1
namenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename=sig=src=class=1
name=sigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsigsig=src=class=1
name=sig=srcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrcsrc=class=1
name=sig=src=classclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclassclass=1
name=sig=src=class=11111111
virtual void CFunctor6<void ()=0F B6 41 51=pdb=CFunctor6<void (*)(struct dlight_t near *,struct msurface2_t near *,struct matrix3x4_t near &,unsigned int,bool,bool),struct dlight_t near *,struct msurface2_t near *,struct matrix3x4_t,unsigned int,bool,bool,class CRefCounted1<class CFunctor,class CRefCountServiceBase<1,class CRefMT>>>=3
virtual unsigned int CryptoPP::PK_Signer::Sign()=55 8B EC 6A FF 68 ? ? ? ? 64 ? ? ? ? ? 50 56 57 A1 ? ? ? ? 33 C5 50 8D 45 F4 64 ? ? ? ? ? 8B 75 0C=pdb=CryptoPP::TF_SignerImpl<struct CryptoPP::TF_SignatureSchemeOptions<class CryptoPP::TF_SS<struct CryptoPP::PKCS1v15,class CryptoPP::SHA1,struct CryptoPP::RSA,int>,struct CryptoPP::RSA,class CryptoPP::PKCS1v15_SignatureMessageEncodingMethod,class CryptoPP::SHA1>>=11
virtual bool CryptoPP::PK_Verifier::Verify()=55 8B EC 6A FF 68 ? ? ? ? 64 ? ? ? ? ? 50 53 56 A1=pdb=CryptoPP::TF_VerifierImpl<struct CryptoPP::TF_SignatureSchemeOptions<class CryptoPP::TF_SS<struct CryptoPP::PKCS1v15,class CryptoPP::SHA1,struct CryptoPP::RSA,int>,struct CryptoPP::RSA,class CryptoPP::PKCS1v15_SignatureMessageEncodingMethod,class CryptoPP::SHA1>>=11
virtual void CFunctor7<void ()=0F B6 41 4C=pdb=CFunctor7<void (*)(class Vector near &,class QAngle near &,class Vector near &,class Vector near &,class Color,class IMaterial near *,bool),class Vector,class QAngle,class Vector,class Vector,class Color,class IMaterial near *,bool,class CRefCounted1<class CFunctor,class CRefCountServiceBase<1,class CRefMT>>>=3
